export interface DetailedCourse {
  id: number;
  title: string;
  description: string;
  instructor: string;
  duration: string;
  students: number;
  rating: number;
  image: string;
  price: string;
  category: string;
  syllabus: string[];
  whatYouLearn: string[];
  prerequisites: string[];
  certification: string;
}

export const detailedCoursesData: DetailedCourse[] = [
  // CS-IT Courses
  {
    id: 1,
    title: "Python Fundamental",
    description: "Master the basics of Python programming with hands-on projects and real-world applications. This comprehensive course covers everything from basic syntax to advanced programming concepts.",
    instructor: "Alex Johnson",
    duration: "8 weeks",
    students: 1250,
    rating: 4.8,
    image: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹4,999",
    category: "cs-it",
    syllabus: [
      "Python Installation & Setup",
      "Variables and Data Types",
      "Control Structures (if/else, loops)",
      "Functions and Modules",
      "File Handling",
      "Exception Handling",
      "Object-Oriented Programming",
      "Libraries and Packages",
      "Database Connectivity",
      "GUI Development Basics",
      "Web Scraping",
      "Final Project"
    ],
    whatYouLearn: [
      "Write clean and efficient Python code",
      "Understand object-oriented programming concepts",
      "Handle files and databases",
      "Create GUI applications",
      "Build web scraping tools",
      "Debug and test Python programs"
    ],
    prerequisites: ["Basic computer knowledge", "No prior programming experience required"],
    certification: "Certificate of Completion"
  },
  {
    id: 2,
    title: "Advanced Python",
    description: "Take your Python skills to the next level with advanced concepts, frameworks, and best practices. Perfect for developers looking to master Python development.",
    instructor: "Sarah Chen",
    duration: "10 weeks",
    students: 890,
    rating: 4.9,
    image: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹7,999",
    category: "cs-it",
    syllabus: [
      "Advanced OOP Concepts",
      "Decorators and Generators",
      "Context Managers",
      "Multithreading and Multiprocessing",
      "Regular Expressions",
      "Web Development with Flask/Django",
      "API Development",
      "Testing and Debugging",
      "Performance Optimization",
      "Design Patterns",
      "Deployment Strategies",
      "Capstone Project"
    ],
    whatYouLearn: [
      "Master advanced Python programming techniques",
      "Build scalable web applications",
      "Implement design patterns",
      "Optimize code performance",
      "Create RESTful APIs",
      "Deploy Python applications"
    ],
    prerequisites: ["Python Fundamental knowledge", "Basic programming experience"],
    certification: "Advanced Python Developer Certificate"
  },
  {
    id: 3,
    title: "Website Development",
    description: "Learn to build responsive websites using HTML, CSS, JavaScript, and modern frameworks. Create stunning web experiences from scratch.",
    instructor: "Mike Davis",
    duration: "12 weeks",
    students: 2100,
    rating: 4.7,
    image: "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹8,999",
    category: "cs-it",
    syllabus: [
      "HTML5 Fundamentals",
      "CSS3 and Responsive Design",
      "JavaScript Basics",
      "DOM Manipulation",
      "CSS Frameworks (Bootstrap)",
      "JavaScript ES6+ Features",
      "AJAX and Fetch API",
      "Version Control with Git",
      "Web Performance Optimization",
      "Cross-browser Compatibility",
      "SEO Basics",
      "Portfolio Project"
    ],
    whatYouLearn: [
      "Create responsive web layouts",
      "Master modern CSS techniques",
      "Build interactive web applications",
      "Optimize website performance",
      "Implement SEO best practices",
      "Use version control effectively"
    ],
    prerequisites: ["Basic computer skills", "No prior web development experience required"],
    certification: "Web Developer Certificate"
  },
  {
    id: 4,
    title: "Web Application Development",
    description: "Build full-stack web applications using modern technologies and industry best practices. Learn both frontend and backend development.",
    instructor: "Lisa Wang",
    duration: "16 weeks",
    students: 1450,
    rating: 4.8,
    image: "https://images.pexels.com/photos/11035386/pexels-photo-11035386.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹12,999",
    category: "cs-it",
    syllabus: [
      "Frontend Frameworks (React/Vue)",
      "State Management",
      "Backend Development (Node.js)",
      "Database Design and Management",
      "RESTful API Development",
      "Authentication and Authorization",
      "Real-time Communication",
      "Testing Strategies",
      "Deployment and DevOps",
      "Security Best Practices",
      "Performance Monitoring",
      "Full-Stack Project"
    ],
    whatYouLearn: [
      "Build complete web applications",
      "Master frontend and backend technologies",
      "Implement secure authentication systems",
      "Design and manage databases",
      "Deploy applications to cloud platforms",
      "Follow industry best practices"
    ],
    prerequisites: ["HTML, CSS, JavaScript knowledge", "Basic programming experience"],
    certification: "Full-Stack Developer Certificate"
  },
  {
    id: 5,
    title: "DBMS & SQL",
    description: "Master database management systems and SQL queries for efficient data handling. Learn to design, implement, and optimize databases.",
    instructor: "John Smith",
    duration: "6 weeks",
    students: 980,
    rating: 4.6,
    image: "https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹5,999",
    category: "cs-it",
    syllabus: [
      "Database Fundamentals",
      "Relational Database Design",
      "SQL Basics and Advanced Queries",
      "Joins and Subqueries",
      "Stored Procedures and Functions",
      "Database Normalization",
      "Indexing and Performance Tuning",
      "Backup and Recovery",
      "Database Security",
      "NoSQL Databases Introduction",
      "Data Warehousing Concepts",
      "Practical Database Project"
    ],
    whatYouLearn: [
      "Design efficient database schemas",
      "Write complex SQL queries",
      "Optimize database performance",
      "Implement database security measures",
      "Understand NoSQL databases",
      "Manage database backups and recovery"
    ],
    prerequisites: ["Basic computer knowledge", "Logical thinking ability"],
    certification: "Database Administrator Certificate"
  },
  {
    id: 6,
    title: "AI & ML",
    description: "Dive into Artificial Intelligence and Machine Learning with practical implementations. Learn to build intelligent systems and predictive models.",
    instructor: "Dr. Emily Brown",
    duration: "14 weeks",
    students: 1680,
    rating: 4.9,
    image: "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹15,999",
    category: "cs-it",
    syllabus: [
      "Introduction to AI and ML",
      "Python for Data Science",
      "Statistics and Probability",
      "Data Preprocessing",
      "Supervised Learning Algorithms",
      "Unsupervised Learning",
      "Deep Learning Fundamentals",
      "Neural Networks",
      "Computer Vision",
      "Natural Language Processing",
      "Model Evaluation and Deployment",
      "AI/ML Project Portfolio"
    ],
    whatYouLearn: [
      "Understand AI and ML concepts",
      "Build predictive models",
      "Implement deep learning algorithms",
      "Work with computer vision",
      "Process natural language",
      "Deploy ML models in production"
    ],
    prerequisites: ["Python programming", "Basic mathematics", "Statistics knowledge helpful"],
    certification: "AI/ML Specialist Certificate"
  },
  {
    id: 7,
    title: "Cloud Computing (AWS)",
    description: "Master Amazon Web Services and cloud computing fundamentals. Learn to deploy, manage, and scale applications in the cloud.",
    instructor: "David Wilson",
    duration: "12 weeks",
    students: 1120,
    rating: 4.7,
    image: "https://images.pexels.com/photos/1181298/pexels-photo-1181298.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹10,999",
    category: "cs-it",
    syllabus: [
      "Cloud Computing Fundamentals",
      "AWS Core Services",
      "EC2 and Virtual Machines",
      "Storage Solutions (S3, EBS)",
      "Database Services (RDS, DynamoDB)",
      "Networking and Security",
      "Load Balancing and Auto Scaling",
      "Serverless Computing (Lambda)",
      "DevOps and CI/CD",
      "Monitoring and Logging",
      "Cost Optimization",
      "AWS Certification Preparation"
    ],
    whatYouLearn: [
      "Deploy applications on AWS",
      "Design scalable cloud architectures",
      "Implement security best practices",
      "Manage cloud costs effectively",
      "Use serverless technologies",
      "Prepare for AWS certifications"
    ],
    prerequisites: ["Basic networking knowledge", "Linux command line familiarity"],
    certification: "AWS Cloud Practitioner Ready"
  },
  {
    id: 8,
    title: "Networking Fundamentals",
    description: "Understand computer networking concepts, protocols, and technologies. Build a strong foundation for network administration and security.",
    instructor: "Network Expert",
    duration: "8 weeks",
    students: 750,
    rating: 4.5,
    image: "https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹6,999",
    category: "cs-it",
    syllabus: [
      "Network Basics and OSI Model",
      "TCP/IP Protocol Suite",
      "Ethernet and LAN Technologies",
      "Routing and Switching",
      "Network Security Fundamentals",
      "Wireless Networking",
      "Network Troubleshooting",
      "VPN and Remote Access",
      "Network Monitoring Tools",
      "IPv6 Implementation",
      "Network Design Principles",
      "Hands-on Lab Exercises"
    ],
    whatYouLearn: [
      "Understand network protocols",
      "Configure routers and switches",
      "Implement network security",
      "Troubleshoot network issues",
      "Design network topologies",
      "Monitor network performance"
    ],
    prerequisites: ["Basic computer knowledge", "Interest in technology"],
    certification: "Networking Fundamentals Certificate"
  },
  {
    id: 9,
    title: "Linux & DevOps Basic",
    description: "Learn Linux system administration and DevOps practices. Master command line, automation, and deployment strategies.",
    instructor: "Linux Guru",
    duration: "10 weeks",
    students: 890,
    rating: 4.6,
    image: "https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹8,999",
    category: "cs-it",
    syllabus: [
      "Linux Installation and Setup",
      "Command Line Mastery",
      "File System and Permissions",
      "Process Management",
      "Shell Scripting",
      "Package Management",
      "System Monitoring",
      "Version Control with Git",
      "CI/CD Pipelines",
      "Containerization (Docker)",
      "Infrastructure as Code",
      "DevOps Best Practices"
    ],
    whatYouLearn: [
      "Master Linux command line",
      "Write shell scripts",
      "Implement CI/CD pipelines",
      "Use containerization technologies",
      "Automate system administration",
      "Follow DevOps methodologies"
    ],
    prerequisites: ["Basic computer skills", "Command line interest"],
    certification: "Linux & DevOps Certificate"
  },
  {
    id: 10,
    title: "GUI Development",
    description: "Create desktop applications with graphical user interfaces using modern frameworks and tools.",
    instructor: "GUI Specialist",
    duration: "8 weeks",
    students: 650,
    rating: 4.4,
    image: "https://images.pexels.com/photos/1181354/pexels-photo-1181354.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹7,999",
    category: "cs-it",
    syllabus: [
      "GUI Design Principles",
      "Tkinter for Python",
      "Event-Driven Programming",
      "Layout Management",
      "Widgets and Controls",
      "Data Binding",
      "File Dialogs and Menus",
      "Graphics and Animation",
      "Database Integration",
      "Application Packaging",
      "Cross-Platform Development",
      "GUI Project Development"
    ],
    whatYouLearn: [
      "Design user-friendly interfaces",
      "Build desktop applications",
      "Handle user interactions",
      "Integrate with databases",
      "Package applications for distribution",
      "Create cross-platform GUIs"
    ],
    prerequisites: ["Python programming knowledge", "Basic programming concepts"],
    certification: "GUI Developer Certificate"
  },

  // Electronics Courses
  {
    id: 11,
    title: "PLC Hardware and Programming",
    description: "Learn PLC programming and hardware configuration for industrial automation systems. Master the fundamentals of programmable logic controllers.",
    instructor: "Robert Wilson",
    duration: "10 weeks",
    students: 650,
    rating: 4.7,
    image: "https://images.pexels.com/photos/159298/gears-cogs-machine-machinery-159298.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹9,999",
    category: "electronics",
    syllabus: [
      "PLC Fundamentals",
      "Hardware Components",
      "Ladder Logic Programming",
      "Input/Output Configuration",
      "Timer and Counter Functions",
      "Data Handling",
      "Communication Protocols",
      "HMI Integration",
      "Troubleshooting Techniques",
      "Safety Systems",
      "Industrial Applications",
      "Hands-on Projects"
    ],
    whatYouLearn: [
      "Program PLCs using ladder logic",
      "Configure I/O modules",
      "Design automation systems",
      "Implement safety protocols",
      "Troubleshoot PLC systems",
      "Integrate with HMI systems"
    ],
    prerequisites: ["Basic electrical knowledge", "Understanding of industrial processes"],
    certification: "PLC Programming Certificate"
  },
  {
    id: 12,
    title: "Industrial Sensors and Instrumentation",
    description: "Understand various industrial sensors and instrumentation techniques for automation. Learn to select and implement appropriate sensing solutions.",
    instructor: "Maria Garcia",
    duration: "8 weeks",
    students: 420,
    rating: 4.5,
    image: "https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹7,999",
    category: "electronics",
    syllabus: [
      "Sensor Fundamentals",
      "Temperature Sensors",
      "Pressure Sensors",
      "Flow Measurement",
      "Level Sensors",
      "Proximity Sensors",
      "Signal Conditioning",
      "Data Acquisition Systems",
      "Calibration Techniques",
      "Sensor Networks",
      "Wireless Sensors",
      "Practical Applications"
    ],
    whatYouLearn: [
      "Select appropriate sensors for applications",
      "Design measurement systems",
      "Implement signal conditioning",
      "Calibrate instrumentation",
      "Build sensor networks",
      "Troubleshoot measurement issues"
    ],
    prerequisites: ["Basic electronics knowledge", "Understanding of measurement principles"],
    certification: "Instrumentation Specialist Certificate"
  },
  {
    id: 13,
    title: "Industrial Communication & Networking",
    description: "Master industrial communication protocols and networking technologies for automation systems.",
    instructor: "Tech Expert",
    duration: "9 weeks",
    students: 380,
    rating: 4.6,
    image: "https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹8,999",
    category: "electronics",
    syllabus: [
      "Industrial Communication Basics",
      "Fieldbus Systems",
      "Ethernet/IP Protocol",
      "Modbus Communication",
      "Profibus and Profinet",
      "DeviceNet Protocol",
      "Wireless Industrial Networks",
      "Network Security",
      "Troubleshooting Networks",
      "Integration Strategies",
      "Future Technologies",
      "Practical Implementation"
    ],
    whatYouLearn: [
      "Implement industrial communication protocols",
      "Design network architectures",
      "Configure fieldbus systems",
      "Ensure network security",
      "Troubleshoot communication issues",
      "Integrate diverse systems"
    ],
    prerequisites: ["Basic networking knowledge", "Industrial automation basics"],
    certification: "Industrial Networking Certificate"
  },
  {
    id: 14,
    title: "Industrial Electrical Systems",
    description: "Understand electrical systems in industrial environments, including power distribution, motor control, and safety systems.",
    instructor: "Electrical Engineer",
    duration: "12 weeks",
    students: 520,
    rating: 4.7,
    image: "https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹10,999",
    category: "electronics",
    syllabus: [
      "Electrical Safety Standards",
      "Power Distribution Systems",
      "Motor Control Circuits",
      "Variable Frequency Drives",
      "Protection Systems",
      "Grounding and Bonding",
      "Electrical Measurements",
      "Power Quality Analysis",
      "Energy Management",
      "Maintenance Strategies",
      "Code Compliance",
      "System Design Projects"
    ],
    whatYouLearn: [
      "Design electrical distribution systems",
      "Implement motor control solutions",
      "Ensure electrical safety compliance",
      "Analyze power quality issues",
      "Develop maintenance programs",
      "Optimize energy consumption"
    ],
    prerequisites: ["Basic electrical knowledge", "Understanding of electrical circuits"],
    certification: "Industrial Electrical Systems Certificate"
  },
  {
    id: 15,
    title: "HMI & SCADA Designing",
    description: "Learn to design and implement Human Machine Interface and SCADA systems for industrial automation and monitoring.",
    instructor: "SCADA Specialist",
    duration: "10 weeks",
    students: 450,
    rating: 4.8,
    image: "https://images.pexels.com/photos/1181354/pexels-photo-1181354.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹9,999",
    category: "electronics",
    syllabus: [
      "HMI Design Principles",
      "SCADA System Architecture",
      "Data Acquisition Methods",
      "Alarm Management",
      "Trending and Reporting",
      "Security Implementation",
      "Database Integration",
      "Communication Protocols",
      "System Testing",
      "Maintenance Procedures",
      "Industry Standards",
      "Complete System Design"
    ],
    whatYouLearn: [
      "Design intuitive HMI interfaces",
      "Implement SCADA systems",
      "Configure data acquisition",
      "Manage alarms effectively",
      "Ensure system security",
      "Create comprehensive reports"
    ],
    prerequisites: ["Basic automation knowledge", "Computer proficiency"],
    certification: "HMI/SCADA Designer Certificate"
  },

  // Machine Design Courses
  {
    id: 16,
    title: "Solid Works",
    description: "Master 3D CAD design and simulation using SolidWorks for mechanical design projects. Learn to create professional engineering drawings.",
    instructor: "James Taylor",
    duration: "10 weeks",
    students: 920,
    rating: 4.7,
    image: "https://images.pexels.com/photos/8386426/pexels-photo-8386426.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹8,999",
    category: "machine-design",
    syllabus: [
      "SolidWorks Interface",
      "Sketching Fundamentals",
      "3D Modeling Techniques",
      "Assembly Design",
      "Drawing Creation",
      "Surface Modeling",
      "Sheet Metal Design",
      "Simulation Basics",
      "Motion Analysis",
      "Design Optimization",
      "Rendering and Visualization",
      "Industry Projects"
    ],
    whatYouLearn: [
      "Create 3D models and assemblies",
      "Generate engineering drawings",
      "Perform basic simulations",
      "Design sheet metal parts",
      "Create photorealistic renders",
      "Optimize designs for manufacturing"
    ],
    prerequisites: ["Basic mechanical engineering knowledge", "Computer proficiency"],
    certification: "SolidWorks Professional Certificate"
  },
  {
    id: 17,
    title: "CATIA V5",
    description: "Learn advanced 3D modeling and surface design using CATIA V5 for automotive and aerospace applications.",
    instructor: "CATIA Expert",
    duration: "12 weeks",
    students: 680,
    rating: 4.8,
    image: "https://images.pexels.com/photos/8386434/pexels-photo-8386434.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹12,999",
    category: "machine-design",
    syllabus: [
      "CATIA V5 Environment",
      "Part Design Workbench",
      "Assembly Design",
      "Drafting Workbench",
      "Surface Design",
      "Generative Shape Design",
      "Sheet Metal Design",
      "Kinematics Simulation",
      "Finite Element Analysis",
      "DMU Navigation",
      "Advanced Modeling",
      "Industry Case Studies"
    ],
    whatYouLearn: [
      "Master CATIA V5 interface and tools",
      "Create complex 3D models",
      "Design advanced surfaces",
      "Perform kinematic analysis",
      "Generate technical drawings",
      "Work on real industry projects"
    ],
    prerequisites: ["Mechanical engineering background", "3D modeling experience helpful"],
    certification: "CATIA V5 Specialist Certificate"
  },
  {
    id: 18,
    title: "AutoCAD",
    description: "Create precise 2D and 3D drawings using AutoCAD for architectural and engineering designs. Master the industry standard drafting tool.",
    instructor: "CAD Professional",
    duration: "8 weeks",
    students: 1340,
    rating: 4.6,
    image: "https://images.pexels.com/photos/3862130/pexels-photo-3862130.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹6,999",
    category: "machine-design",
    syllabus: [
      "AutoCAD Interface and Setup",
      "Basic Drawing Commands",
      "Precision Drawing Techniques",
      "Editing and Modification",
      "Layers and Properties",
      "Dimensioning and Annotation",
      "Blocks and Attributes",
      "3D Modeling Basics",
      "Layouts and Plotting",
      "Customization Options",
      "Industry Standards",
      "Portfolio Development"
    ],
    whatYouLearn: [
      "Create precise technical drawings",
      "Master 2D and 3D design tools",
      "Implement drafting standards",
      "Customize AutoCAD environment",
      "Prepare drawings for printing",
      "Work efficiently with layers and blocks"
    ],
    prerequisites: ["Basic computer skills", "Understanding of technical drawings helpful"],
    certification: "AutoCAD Professional Certificate"
  },
  {
    id: 19,
    title: "ANSYS",
    description: "Learn finite element analysis and simulation using ANSYS for engineering design validation and optimization.",
    instructor: "Simulation Expert",
    duration: "12 weeks",
    students: 420,
    rating: 4.9,
    image: "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹14,999",
    category: "machine-design",
    syllabus: [
      "Introduction to FEA",
      "ANSYS Workbench Environment",
      "Geometry and Meshing",
      "Structural Analysis",
      "Thermal Analysis",
      "Fluid Flow Analysis",
      "Modal Analysis",
      "Fatigue Analysis",
      "Optimization Studies",
      "Result Interpretation",
      "Advanced Simulations",
      "Industry Applications"
    ],
    whatYouLearn: [
      "Perform finite element analysis",
      "Validate engineering designs",
      "Optimize product performance",
      "Analyze structural behavior",
      "Simulate thermal effects",
      "Interpret simulation results"
    ],
    prerequisites: ["Engineering background", "Basic CAD knowledge", "Understanding of mechanics"],
    certification: "ANSYS Simulation Certificate"
  },
  {
    id: 20,
    title: "Fluid Sim",
    description: "Master fluid simulation and computational fluid dynamics for engineering applications and design optimization.",
    instructor: "CFD Specialist",
    duration: "10 weeks",
    students: 280,
    rating: 4.7,
    image: "https://images.pexels.com/photos/1181298/pexels-photo-1181298.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹11,999",
    category: "machine-design",
    syllabus: [
      "Fluid Mechanics Fundamentals",
      "CFD Theory and Methods",
      "Mesh Generation",
      "Boundary Conditions",
      "Turbulence Modeling",
      "Heat Transfer Analysis",
      "Multiphase Flows",
      "Post-Processing",
      "Validation Techniques",
      "Optimization Studies",
      "Industry Case Studies",
      "Advanced Applications"
    ],
    whatYouLearn: [
      "Understand fluid dynamics principles",
      "Perform CFD simulations",
      "Analyze flow patterns",
      "Optimize fluid systems",
      "Validate simulation results",
      "Apply CFD to real problems"
    ],
    prerequisites: ["Engineering background", "Fluid mechanics knowledge", "Mathematical foundation"],
    certification: "CFD Analysis Certificate"
  },

  // Other Courses
  {
    id: 21,
    title: "Photoshop",
    description: "Master photo editing, digital art, and graphic design using Adobe Photoshop. Create stunning visual content for various media.",
    instructor: "Creative Studio",
    duration: "6 weeks",
    students: 1890,
    rating: 4.7,
    image: "https://images.pexels.com/photos/34153/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=400",
    price: "₹4,999",
    category: "other",
    syllabus: [
      "Photoshop Interface",
      "Basic Tools and Techniques",
      "Layers and Masks",
      "Color Correction",
      "Photo Retouching",
      "Digital Painting",
      "Typography Design",
      "Web Graphics",
      "Print Design",
      "Advanced Compositing",
      "Automation and Actions",
      "Portfolio Creation"
    ],
    whatYouLearn: [
      "Edit and enhance photographs",
      "Create digital artwork",
      "Design graphics for web and print",
      "Master advanced selection techniques",
      "Work with layers and masks",
      "Create professional compositions"
    ],
    prerequisites: ["Basic computer skills", "Creative interest"],
    certification: "Photoshop Specialist Certificate"
  },
  {
    id: 22,
    title: "Blender",
    description: "Create stunning 3D models, animations, and visual effects using Blender. Master the complete 3D creation pipeline.",
    instructor: "3D Artist",
    duration: "12 weeks",
    students: 1120,
    rating: 4.8,
    image: "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹9,999",
    category: "other",
    syllabus: [
      "Blender Interface and Navigation",
      "3D Modeling Fundamentals",
      "Sculpting Techniques",
      "Materials and Texturing",
      "Lighting and Rendering",
      "Animation Basics",
      "Rigging and Character Animation",
      "Particle Systems",
      "Physics Simulations",
      "Compositing",
      "Video Editing",
      "Final Project Creation"
    ],
    whatYouLearn: [
      "Create 3D models and scenes",
      "Animate characters and objects",
      "Apply materials and textures",
      "Set up lighting and cameras",
      "Render high-quality images",
      "Create visual effects"
    ],
    prerequisites: ["Basic computer skills", "Interest in 3D graphics"],
    certification: "Blender 3D Artist Certificate"
  },
  {
    id: 23,
    title: "MS Office",
    description: "Master Microsoft Office suite including Word, Excel, PowerPoint, and Outlook for professional productivity.",
    instructor: "Office Expert",
    duration: "4 weeks",
    students: 2340,
    rating: 4.5,
    image: "https://images.pexels.com/photos/590020/pexels-photo-590020.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹2,999",
    category: "other",
    syllabus: [
      "Word Processing with MS Word",
      "Document Formatting",
      "Excel Spreadsheet Basics",
      "Formulas and Functions",
      "PowerPoint Presentations",
      "Slide Design and Animation",
      "Outlook Email Management",
      "Calendar and Tasks",
      "Data Analysis in Excel",
      "Mail Merge",
      "Collaboration Features",
      "Productivity Tips"
    ],
    whatYouLearn: [
      "Create professional documents",
      "Build effective spreadsheets",
      "Design compelling presentations",
      "Manage email efficiently",
      "Collaborate on documents",
      "Increase workplace productivity"
    ],
    prerequisites: ["Basic computer knowledge"],
    certification: "MS Office Proficiency Certificate"
  },
  {
    id: 24,
    title: "MS Excel Advanced",
    description: "Master advanced Excel functions, macros, and data analysis techniques for professional data management and reporting.",
    instructor: "Excel Guru",
    duration: "6 weeks",
    students: 1560,
    rating: 4.8,
    image: "https://images.pexels.com/photos/590020/pexels-photo-590020.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹5,999",
    category: "other",
    syllabus: [
      "Advanced Formulas and Functions",
      "Data Validation and Cleaning",
      "Pivot Tables and Charts",
      "Macro Programming with VBA",
      "Data Analysis Tools",
      "Dashboard Creation",
      "Financial Modeling",
      "Statistical Analysis",
      "Database Functions",
      "Power Query and Power Pivot",
      "Automation Techniques",
      "Real-world Projects"
    ],
    whatYouLearn: [
      "Master complex Excel formulas",
      "Create interactive dashboards",
      "Automate tasks with macros",
      "Perform advanced data analysis",
      "Build financial models",
      "Use Power BI integration"
    ],
    prerequisites: ["Basic Excel knowledge", "Understanding of spreadsheet concepts"],
    certification: "Excel Expert Certificate"
  },
  {
    id: 25,
    title: "MIT App Inventor",
    description: "Create mobile applications without coding using MIT App Inventor's visual programming environment.",
    instructor: "App Developer",
    duration: "5 weeks",
    students: 890,
    rating: 4.6,
    image: "https://images.pexels.com/photos/1181354/pexels-photo-1181354.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹3,999",
    category: "other",
    syllabus: [
      "App Inventor Interface",
      "Visual Programming Concepts",
      "User Interface Design",
      "Event-Driven Programming",
      "Data Storage",
      "Sensors and Hardware",
      "Web Services Integration",
      "App Testing and Debugging",
      "Publishing to App Stores",
      "Advanced Components",
      "Game Development",
      "Portfolio Apps"
    ],
    whatYouLearn: [
      "Build mobile apps visually",
      "Design user interfaces",
      "Handle user interactions",
      "Work with device sensors",
      "Store and retrieve data",
      "Publish apps to stores"
    ],
    prerequisites: ["Basic computer skills", "Logical thinking"],
    certification: "Mobile App Developer Certificate"
  },
  {
    id: 26,
    title: "Kodu",
    description: "Learn game development and programming concepts using Microsoft Kodu Game Lab's visual programming language.",
    instructor: "Game Designer",
    duration: "4 weeks",
    students: 650,
    rating: 4.4,
    image: "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹2,999",
    category: "other",
    syllabus: [
      "Kodu Game Lab Introduction",
      "Visual Programming Basics",
      "Character Creation and Control",
      "World Building",
      "Game Logic and Rules",
      "Scoring Systems",
      "Sound and Music",
      "Game Testing",
      "Sharing Games",
      "Advanced Techniques",
      "Game Design Principles",
      "Final Game Project"
    ],
    whatYouLearn: [
      "Create 3D games visually",
      "Understand programming logic",
      "Design game worlds",
      "Implement game mechanics",
      "Add sound and effects",
      "Share games with others"
    ],
    prerequisites: ["Basic computer skills", "Interest in games"],
    certification: "Game Development Certificate"
  },
  {
    id: 27,
    title: "Scratch",
    description: "Learn programming fundamentals through Scratch's visual programming language. Perfect for beginners and educators.",
    instructor: "Programming Teacher",
    duration: "4 weeks",
    students: 1240,
    rating: 4.7,
    image: "https://images.pexels.com/photos/1181354/pexels-photo-1181354.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹2,499",
    category: "other",
    syllabus: [
      "Scratch Interface and Basics",
      "Sprites and Costumes",
      "Motion and Animation",
      "Events and Control",
      "Variables and Data",
      "Loops and Conditions",
      "Sound and Music",
      "Interactive Stories",
      "Game Development",
      "Sharing Projects",
      "Advanced Techniques",
      "Creative Projects"
    ],
    whatYouLearn: [
      "Understand programming concepts",
      "Create animations and games",
      "Use logical thinking",
      "Build interactive stories",
      "Share creative projects",
      "Prepare for text-based coding"
    ],
    prerequisites: ["Basic computer skills", "No programming experience needed"],
    certification: "Scratch Programming Certificate"
  },
  {
    id: 28,
    title: "Teachable Machines",
    description: "Explore machine learning concepts using Google's Teachable Machine platform. Create AI models without coding.",
    instructor: "AI Educator",
    duration: "3 weeks",
    students: 780,
    rating: 4.5,
    image: "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=400",
    price: "₹1,999",
    category: "other",
    syllabus: [
      "Introduction to Machine Learning",
      "Teachable Machine Platform",
      "Image Classification Models",
      "Audio Recognition Models",
      "Pose Detection Models",
      "Training and Testing",
      "Model Evaluation",
      "Exporting Models",
      "Integration with Projects",
      "Ethics in AI",
      "Real-world Applications",
      "Creative AI Projects"
    ],
    whatYouLearn: [
      "Understand machine learning basics",
      "Create AI models visually",
      "Train image classifiers",
      "Build audio recognition systems",
      "Export models for use",
      "Apply AI ethically"
    ],
    prerequisites: ["Basic computer skills", "Curiosity about AI"],
    certification: "AI Literacy Certificate"
  }
];